services:
  neo4j:
    image: neo4j:community
    container_name: medai_neo4j
    ports:
      - "7474:7474" # HTTP Interface (Browser)
      - "7687:7687" # Bolt Protocol (Application access)
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./data/neo4j:/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: ai
    ports:
      - "5532:5432"
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    restart: unless-stopped
